<?php

namespace App\Http\Controllers\Tenant;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreTenantOrderRequest;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Produk;
use App\Models\Tenant;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\View\View;

class TenantOrderController extends Controller
{
    /**
     * Show the checkout form for a specific product.
     *
     * Validates:
     * - Product belongs to this tenant
     * - Product is active (status = true)
     * - Product is in stock (stok > 0)
     */
    public function create(Tenant $tenant, Produk $produk): View
    {
        // Ensure product belongs to this tenant
        if ($produk->tenant_id !== $tenant->id) {
            abort(404);
        }

        // Ensure product is available for purchase
        if (! $produk->status || $produk->stok <= 0) {
            abort(404, 'Produk tidak tersedia untuk dibeli.');
        }

        // Load tenant profile for the checkout page layout
        $tenant->load(['profilUsaha', 'template']);

        $templateSlug = $tenant->template?->slug_key ?? 'minimalist';
        $viewName = "tenant.templates.{$templateSlug}.checkout";

        if (! view()->exists($viewName)) {
            $viewName = 'tenant.templates.minimalist.checkout';
        }

        return view($viewName, [
            'tenant' => $tenant,
            'profil' => $tenant->profilUsaha,
            'produk' => $produk,
        ]);
    }

    /**
     * Process the checkout and create an order.
     *
     * This method uses a strict database transaction with pessimistic locking
     * to prevent race conditions when multiple buyers checkout simultaneously.
     *
     * Transaction steps:
     * 1. Lock the product row (SELECT ... FOR UPDATE)
     * 2. Validate stock availability
     * 3. Calculate total on the backend (NEVER trust frontend prices)
     * 4. Create Order
     * 5. Create OrderItem
     * 6. Decrement product stock
     * 7. Create Invoice
     */
    public function store(StoreTenantOrderRequest $request, Tenant $tenant, Produk $produk): RedirectResponse
    {
        // Guard: produk must belong to tenant + be active
        abort_if($produk->tenant_id !== $tenant->id || ! $produk->status, 404);

        // Guard: if product has variants, buyer must choose one
        if ($produk->hasVariants() && blank($request->validated('varian'))) {
            return back()
                ->withInput()
                ->withErrors(['varian' => "Pilih {$produk->varian_label} terlebih dahulu."]);
        }

        // Guard: if variant chosen, must be a valid option
        if ($produk->hasVariants() && ! in_array($request->validated('varian'), $produk->varian_opsi_array, true)) {
            return back()
                ->withInput()
                ->withErrors(['varian' => 'Varian yang dipilih tidak valid.']);
        }

        try {
            $order = DB::transaction(function () use ($request, $tenant, $produk) {
                // Lock product row to prevent oversell
                $locked = Produk::where('id', $produk->id)->lockForUpdate()->first();

                if (! $locked || $locked->stok < $request->validated('jumlah')) {
                    throw new \RuntimeException('Stok tidak mencukupi. Silakan kurangi jumlah pesanan.');
                }

                $subtotal = $locked->harga * $request->validated('jumlah');

                $order = Order::create([
                    'tenant_id' => $tenant->id,
                    'kode_order' => $this->generateKodeOrder(),
                    'nama_pembeli' => $request->validated('nama_pembeli'),
                    'email_pembeli' => $request->validated('email_pembeli'),
                    'no_hp_pembeli' => $request->validated('no_hp_pembeli'),
                    'alamat_pengiriman' => $request->validated('alamat_pengiriman'),
                    'catatan_pembeli' => $request->validated('catatan_pembeli'),
                    'total_harga' => $subtotal,
                    'status' => 'pending',
                    // public_token auto-generated by Order::booted()
                ]);

                $order->orderItems()->create([
                    'produk_id' => $locked->id,
                    'jumlah' => $request->validated('jumlah'),
                    'varian' => $request->validated('varian'),
                    'harga' => $locked->harga,
                    'subtotal' => $subtotal,
                ]);

                $order->invoice()->create([
                    'nomor_invoice' => $this->generateNomorInvoice(),
                    'qr_code_url' => null,
                    'status_pembayaran' => 'unpaid',
                ]);

                $locked->decrement('stok', $request->validated('jumlah'));

                // Auto-deactivate if out of stock
                if ($locked->stok <= 0) {
                    $locked->update(['status' => false]);
                }

                return $order;
            });
        } catch (\RuntimeException $e) {
            return back()
                ->withInput()
                ->with('error', $e->getMessage());
        }

        return redirect()->route('tenant.order.success', [$tenant, $order]);
    }

    /**
     * Display the order success / confirmation page.
     *
     * Shows order summary, invoice number, and payment instructions.
     */
    public function success(Tenant $tenant, Order $order): View
    {
        // Ensure the order belongs to this tenant
        if ($order->tenant_id !== $tenant->id) {
            abort(404);
        }

        // Eager-load relationships for the confirmation page
        $order->load(['orderItems.produk', 'invoice']);
        $tenant->load(['profilUsaha', 'template']);

        $templateSlug = $tenant->template?->slug_key ?? 'minimalist';
        $viewName = "tenant.templates.{$templateSlug}.order-success";

        if (! view()->exists($viewName)) {
            $viewName = 'tenant.templates.minimalist.order-success';
        }

        return view($viewName, [
            'tenant' => $tenant,
            'profil' => $tenant->profilUsaha,
            'order' => $order,
            'invoice' => $order->invoice,
        ]);
    }

    /**
     * Generate a unique order code.
     * Format: ORD-YYYYMMDD-XXXX (e.g. ORD-20260325-A7K2)
     */
    private function generateKodeOrder(): string
    {
        do {
            $kode = 'ORD-'.date('Ymd').'-'.strtoupper(Str::random(4));
        } while (Order::where('kode_order', $kode)->exists());

        return $kode;
    }

    /**
     * Generate a unique invoice number.
     * Format: INV-YYYYMMDD-XXXX (e.g. INV-20260325-B3M9)
     */
    private function generateNomorInvoice(): string
    {
        do {
            $nomor = 'INV-'.date('Ymd').'-'.strtoupper(Str::random(4));
        } while (Invoice::where('nomor_invoice', $nomor)->exists());

        return $nomor;
    }
}
