services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    container_name: mylinx-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - mylinx-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PHP_OPCACHE_ENABLE=0
    command: >
      sh -c " [ ! -L /var/www/html/public/storage ] && php /var/www/html/artisan
      storage:link || true; php-fpm "

  web:
    image: nginx:1.25-bookworm
    container_name: mylinx-web-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html:ro
      - mylinx-storage:/var/www/html/storage:ro
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    networks:
      - mylinx-network
    depends_on:
      - app

  db:
    image: postgres:16-bookworm
    container_name: mylinx-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mylinx
      POSTGRES_USER: mylinx
      POSTGRES_PASSWORD: secret
    volumes:
      - mylinx-db-data:/var/lib/postgresql/data
    networks:
      - mylinx-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mylinx -d mylinx" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mylinx-db-data:
    driver: local

networks:
  mylinx-network:
    driver: bridge
