server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;

    access_log /var/log/nginx/mylinx-access.log;
    error_log  /var/log/nginx/mylinx-error.log;

    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_read_timeout 300;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }

    location ~* \.(css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|eot)$ {
        expires 7d;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }

    location ~ /\.env {
        deny all;
        return 404;
    }
}
